version: '3'
services:
  ################################### SPARK
  spark:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks/
